name: cashes
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: any
  open_filex: ^4.4.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^6.2.1
  printing: ^5.13.1
  provider: ^6.1.2
  uuid: ^4.4.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
